### ISSUE TITLE
What is the goal of this repo?

### ISSUE THREAD

**Issue by aloisdg** [aalhour/C-Sharp-Algorithms#12]
Hello,

I read that you start this repo as  an interview-preparation project. Now, what do you want to do with it? Keep collecting c# implementation of algorithms? It could be nice to share them on [Rosetta Code](http://rosettacode.org/) or Wikipedia for example.

Also, I wrote algorithms in C# for learning purpose in this [repository](https://github.com/aloisdg/algo). If you want, I can share all of them in a pull request.

Cheers,

**Comment by aalhour** [comment]
Hello,

I am glad you found my repo interesting. 

The purpose of this repo is mainly still for interview preparation. The secondary response however is to act like a research side project under the C# umbrella. I have taken a look at your repo, and I am afraid that your programs won't fit in the context of this repo, since the focus is on general and generic implementations of standard data structures and algorithms. The only program that got me interested is the Levenshtein distance :+1: which is something I studied but put on hold for now. I have implemented the general version of the Edit Distance problem with a helper class that would allow you to customise the weights for special cases such as this, make sure to check it out and give me your feedback. I am sorry that I won't pull your code into this repo.

On a side note, if you wish to contribute to this library, then I will be happy to integrate your contributions, just pick a standard data structure or algorithm that was not implemented in this repo yet, and then create a pull request. All you have to do is basically 1) clone this repo, 2) create your data structure and/or algorithm source code file(s), 3) create an accompanying test file for them under the MainProgram project and test them thoroughly, 4) create your pull request.

Cheers! And thanks for passing by! :)

**Comment by aloisdg** [comment]
Thank you for the answer. I may contribute later. Have a nice day. :)
