### ISSUE TITLE
Open-Addressing Hash Table

### ISSUE THREAD

**Issue by aalhour** [aalhour/C-Sharp-Algorithms#34]
Implement the [Open-Addressing Hash Table](https://en.wikipedia.org/wiki/Open_addressing) Data Structure.

Top priority goes to implementing the the data structure with [Double-Hashing](https://en.wikipedia.org/wiki/Double_hashing) algorithm. Nevertheless, implementing all of the three main Open-Addressing algorithms is always welcome.

The three main Open-Addressing Algorithms:
- Linear Probing.
- Quadratic Probing.
- Double Hashing.

**Comment by SamuelKenney** [comment]
#41

**Comment by aalhour** [comment]
Hello @SamuelKenney, thanks for contributing, I will review the PR in the upcoming days.

**Comment by aalhour** [comment]
Hello @SamuelKenney, I have reviewed your PR and commented on it, please review the comments at your earliest availability.

**Comment by SamuelKenney** [comment]
Hi Ahmad,

I did get a chance to review but have not be able to add the changes you
wrote about. Things have just been incredibly busy. I hope to get to it
soon!

Thanks,

Sam

On Jul 5, 2017 4:34 PM, "Ahmad Alhour" <notifications@github.com> wrote:

Hello @SamuelKenney <https://github.com/samuelkenney>, I have reviewed your
PR and commented on it, please review the comments at your earliest
availability.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aalhour/C-Sharp-Algorithms/issues/34#issuecomment-313218963>,
or mute the thread
