### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by hwgeone** [aalhour/C-Sharp-Algorithms#50]
red back tree ：in _adjustTreeAfterInsertion method，I found a problem which in code:
 if (currentNode != null && currentNode != Root && _safeCheckIsRed(_safeGetParent(currentNode)))
            {
                //
                // STEP 2.A:
                // This is the simplest step: Basically recolor, and bubble up to see if more work is needed.
                if (_safeCheckIsRed(_safeGetSibling(currentNode.Parent)))
                {
                    // If it has a sibling and it is red, then then it has a parent
                    currentNode.Parent.Color = RedBlackTreeColors.Red;//black？

I think right code is  currentNode.Parent.Color = RedBlackTreeColors.Black

**Comment by hwgeone** [comment]
https://github.com/aalhour/C-Sharp-Algorithms/blob/6b2bd0591b0bd10d62d99e71097d0400aaf7c1e9/DataStructures/Trees/RedBlackTree.cs#L237

**Comment by hwgeone** [comment]
Hi @aalhour 

You confirm, look forward to reply
Cheers,
Wei Huang

**Comment by aalhour** [comment]
Hi @hwgeone,

Sorry for the late reply. I am not sure about your proposal, probably my inline comments are misleading, but I think rotation should happen to the right, that's why the sibling gets coloured as Black and the parent as Red. I have implemented your suggestion and visualised the final result of the tree and I got the following:

With current implementation:

```
                 ........4........            
                /                 \           
            ..0.999..          ...10...       
           /         \        /        \      
       ..0.997.       2      .8.      .14.    
      /        \     / \    /   \    /    \   
   .0.972     0.998 1   3   6    9   12    17 
  /      \                 / \      / \   / \ 
0.901   0.996             5   7    11 13 15 18
        /                                     
      0.975                                   
```

With your suggestion:

```
                 .......4......              
                /              \             
            ..0.999..        ...8...         
           /         \      /       \        
       ..0.997.       2     6      ..12.     
      /        \     / \   / \    /     \    
   .0.972     0.998 1   3 5   7   10     15  
  /      \                       / \    / \  
0.901   0.996                   9  11  14 17 
        /                              /   \ 
      0.975                           13   18
```

Notice how the balancing on the right side of the tree differs. It is still a Red-Black Tree, but the colouring logic changed it to strictly become a Right-Leaning RB Tree.

I forgot which subtype of an RB Tree is this (RL or LL), so I think I am going to re-implement it to become LL RB Tree which is much simpler to reason about than the current implementation.

Would you like to submit a PR to re-place the current implementation with a simpler Left-Leaning RB Tree implementation?

Cheers,
Ahmad
