### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by hwgeone** [aalhour/C-Sharp-Algorithms#51]
protected bool _remove(RedBlackTreeNode<TKey> nodeToDelete)
        {
            if (nodeToDelete == null)
                return false;

            // Temporary nodes
            RedBlackTreeNode<TKey> node1, node2;

            // If nodeToDelete has either one child or no children at all
            if (!nodeToDelete.HasLeftChild || !nodeToDelete.HasRightChild)
            {
                node1 = nodeToDelete;
            }
            else
            {
                // nodeToDelete has two children
                node1 = (RedBlackTreeNode<TKey>)base._findNextLarger(nodeToDelete);//why is _findNextLarger
            }

            // Left child case
            if (node1.HasLeftChild)
            {
                node2 = node1.LeftChild;
            }
            else
            {
                node2 = node1.RightChild;
            }

            // If node2 is not null, copy parent references
            if (node2 != null)
                node2.Parent = node1.Parent;

            if (node1.Parent != null)
            {
                if (node1.IsLeftChild)
                {
                    node1.Parent.LeftChild = node2;
                }
                else
                {
                    node1.Parent.RightChild = node2;
                }
            }
            else
            {
                Root = node2;
                Root.Parent = null;
            }

            // Swap values
            if (!node1.IsEqualTo(nodeToDelete))
            {
                nodeToDelete.Value = node1.Value;
            }

            // Adjust the Red-Black Tree rules
            if (node1.Color == RedBlackTreeColors.Black && node2 != null)
            {
                _adjustTreeAfterRemoval(node2);
                Root.Color = RedBlackTreeColors.Black;
            }

            // Decrement the count
            base._count--;

            return true;
        }

  node1 = (RedBlackTreeNode<TKey>)base._findNextLarger(nodeToDelete);  in this code why is find larger but not find smaller.
https://www.cs.usfca.edu/~galles/visualization/RedBlack.html      this  link  shows the process of delete a note,and it process is find a smaller note but not larger note
which is right?

**Comment by aalhour** [comment]
Hello @hwgeone,

Sorry for the late reply. When deleting a tree node that has children it we need to rebalance that branch after deletion, as that node could be linking to a big sub-tree and not just leaf nodes. Regardless of the size of the subtree that the delete operation will mutate, we need to find the next larger element in that subtree in order to find the new root for that subtree, this doesn't mean that we will end up with the largest number in the entire subtree but the next bigger one after the one we're deleting. When we find it we will mark it as the new root of the subtree and then try to re-balance the tree around it.

I hope this makes it clearer for you.

Cheers,
Ahmad

**Comment by aalhour** [comment]
Hello @hwgeone,

I will close the issue for now, if you think this is really a bug, please reopen it with, preferably, a failing unit test to prove that there is a bug.

Cheers,
Ahmad
