### ISSUE TITLE
Fix RedBlackTree impl/test

### ISSUE THREAD

**Issue by PatrykOlejniczak** [aalhour/C-Sharp-Algorithms#81]
Hello,
after downloading the repository, I noticed that not all tests pass. 
e.g. [tests](https://github.com/aalhour/C-Sharp-Algorithms/blob/master/UnitTest/DataStructuresTests/RedBlackTreeTest.cs) related with [RedBlackTree](https://github.com/aalhour/C-Sharp-Algorithms/blob/master/DataStructures/Trees/RedBlackTree.cs). 
I would like to work on these tests or implementation depends on what the problem will turn out to be if nobody else actual work with it?

I can also add some more unit test for that trees.

Regards.

**Comment by aalhour** [comment]
Hello @PatrykOlejniczak,

As I mentioned in the other issue, I'd be more than happy to review and accept contributions but after I get the unit tests fixed. If you can help me with that I'd appreciate it a lot! The problem is that Travis CI no longer runs the unit tests projects and I would like someone to help me fix that.

Cheers,
Ahmad
