### ISSUE TITLE
Fix test/impl AVL trees

### ISSUE THREAD

**Issue by PatrykOlejniczak** [aalhour/C-Sharp-Algorithms#83]
Hello,
same [story just like with RedBlackTree issue](https://github.com/aalhour/C-Sharp-Algorithms/issues/81), I noticed that not all tests pass.
I would like to work on these tests or implementation depends on what the problem will turn out to be.
I will try to add more test cases.

Related with an earlier reported problem https://github.com/aalhour/C-Sharp-Algorithms/issues/76

Regards.

**Comment by gregfra** [comment]
Patryk, I just made a PR to correct the failing subtest. You can review and/or add AVL tree subtests and I can look those over for you.

**Comment by PatrykOlejniczak** [comment]
Hi, for me looks good, thx for do that, but I think repo is dead or susspended (my pr for RBT is hanging a month),  maybe owner say something @aalhour

**Comment by aalhour** [comment]
Hello @PatrykOlejniczak, @gregfra,

I'd be more than happy to review and accept contributions but after I get the unit tests fixed. If you guys can help me with that I'd appreciate it a lot! The problem is that Travis CI no longer runs the unit tests projects and I would like someone to help me fix that.

Cheers,
Ahmad

**Comment by PatrykOlejniczak** [comment]
I'll close this issue fix #76 is already merged.

Thanks @gregfra
